// Turns the golden cases into a database test, so the database gives exactly the app's answers
// (CLAUDE.md hard rule 4).   Run: npm run golden:sql
// Writes supabase/tests/03_golden.test.sql. A Vitest test fails if that file is out of date.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";

const OUT = "supabase/tests/03_golden.test.sql";

export function buildGoldenSql() {
  const casesDir = "tests/golden/cases";
  const charts = { "iocl-20kl": JSON.parse(readFileSync("tests/golden/charts/iocl-20kl.json", "utf8")).rows };
  const cases = readdirSync(casesDir)
    .filter((f) => f.endsWith(".json"))
    .sort()
    .map((f) => ({ file: f, ...JSON.parse(readFileSync(`${casesDir}/${f}`, "utf8")) }));

  const sqlText = (s) => `'${String(s).replace(/'/g, "''")}'`;
  const decimals = (s) => (s.includes(".") ? s.length - s.indexOf(".") - 1 : 0);
  const tests = [];
  const setup = [];

  for (const c of cases) {
    if (c.kind === "dip") {
      const rows = charts[c.chart].map(([d, l]) => `(${d}, ${l})`).join(",\n    ");
      setup.push(`-- Chart for ${c.file}
insert into public.dip_charts (id, pump_id, name, chart_version)
  select 'dddddddd-0000-0000-0000-000000000001', id, 'golden ${c.chart}', 99 from public.pumps limit 1;
insert into public.dip_chart_rows (pump_id, chart_id, dip_cm, volume_l)
  select (select id from public.pumps limit 1), 'dddddddd-0000-0000-0000-000000000001', d, l from (values
    ${rows}) v(d, l);`);
      for (const r of c.readings) {
        const got = `public.dip_to_litres('dddddddd-0000-0000-0000-000000000001', ${r.dipCm})`;
        tests.push(
          r.litres === null
            ? `select is(${got}, null, ${sqlText(`${c.file}: ${r.dipCm} cm is outside the chart`)});`
            : `select is(round(${got}, ${decimals(r.litres)}), ${r.litres}::numeric, ${sqlText(`${c.file}: ${r.dipCm} cm = ${r.litres} L`)});`,
        );
      }
    }
    if (c.kind === "price") {
      setup.push(`-- Prices for ${c.file}
insert into public.pumps (id, name, rules) values ('eeeeeeee-0000-0000-0000-000000000001', 'golden prices', '{}');
insert into public.fuel_prices (pump_id, product, per_litre, starts_on) values
  ${c.prices.map((p) => `('eeeeeeee-0000-0000-0000-000000000001', '${p.product}', ${p.perLitre}, '${p.startsOn}')`).join(",\n  ")};`);
      for (const l of c.lookups) {
        const got = `public.price_for('eeeeeeee-0000-0000-0000-000000000001', '${l.product}', '${l.date}')`;
        tests.push(`select is(${got}, ${l.perLitre === null ? "null" : `${l.perLitre}::numeric`}, ${sqlText(`${c.file}: ${l.product} on ${l.date}`)});`);
      }
    }
    if (c.kind === "businessDate") {
      for (const b of c.cases) {
        tests.push(
          `select is(public.business_date_at('${b.at}'::timestamptz, '${b.dayStart}', 'Asia/Kolkata'), '${b.businessDate}'::date, ${sqlText(`${c.file}: ${b.at}, day starts ${b.dayStart}`)});`,
        );
      }
    }
  }

  return `-- GENERATED by scripts/golden-to-sql.mjs from tests/golden/cases. Don't edit by hand: run npm run golden:sql.
-- The database's maths must give exactly the same answers as the app's (CLAUDE.md hard rule 4).
begin;
create extension if not exists pgtap with schema extensions;
select plan(${tests.length});

${setup.join("\n\n")}

${tests.join("\n")}

select * from finish();
rollback;
`;
}

if (process.argv[1] && process.argv[1].endsWith("golden-to-sql.mjs")) {
  writeFileSync(OUT, buildGoldenSql());
  console.log(`Wrote ${OUT}`);
}
